background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
}

# ЧАСЫ (БЕЛЫЕ)
label {
    monitor =
    text = cmd[update:1000] echo "$TIME"
    color = rgb(ffffff)
    font_size = 90
    font_family = JetBrainsMono NF Bold
    position = 0, 150
    halign = center
    valign = center
}

# ПОЛЕ ВВОДА
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.25
    dots_spacing = 0.4
    dots_center = true
    outer_color = rgb(e8729a)
    inner_color = rgb(ffffff)
    font_color = rgb(000000)
    fade_on_empty = false
    placeholder_text = <span foreground="##e8729a">Введите пароль...</span>
    position = 0, -20
    halign = center
    valign = center
}
