# Базовые настройки для слабого ПК
backend = "xrender";
use-damage = true;
vsync = false;

# Отключение скругления углов
corner-radius = 0;

# Настройка жесткого свечения (обводки)
shadow = true;
shadow-radius = 3;       # Ширина свечения в пикселях (подберите под себя)
shadow-opacity = 1.0;     # Максимальная непрозрачность (черный цвет)

# Смещение тени (0 и 0 центрируют свечение строго по периметру)
shadow-offset-x = -3;    # Должно быть равно значению shadow-radius со знаком минус
shadow-offset-y = -3;    # Должно быть равно значению shadow-radius со знаком минус

# Цвет свечения (черный)
shadow-color = "#000000";
