<<<<<<< HEAD
# === Тени и Кроваво-Красное Свечение ===
shadow = true;
shadow-radius = 20;        # Радиус размытия свечения
shadow-opacity = 0.95;     # Максимальная плотность свечения (почти без прозрачности)
shadow-offset-x = -18;     # Смещение по X для баланса
shadow-offset-y = -18;     # Смещение по Y для баланса

# Кроваво-красный ZXC цвет свечения
shadow-color = "#cc0000"

shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'Conky'",
  "class_g ?= 'Notify-osd'",
  "class_g = 'Cairo-clock'",
  "_GTK_FRAME_EXTENTS@:c"
];

# === Полное отключение прозрачности ===
active-opacity = 1.0;
inactive-opacity = 1.0;
frame-opacity = 1.0;
inactive-opacity-override = false;

# === Полное отключение скругления окон ===
corner-radius = 0;
rounded-corners-exclude = [
  "window_type = 'normal'"
];

# === Полное отключение затухания/анимаций (Fading) ===
fading = false;

# === Настройки производительности (GLX backend) ===
backend = "glx";
vsync = true;
detect-rounded-corners = true;
detect-client-opacity = true;
refresh-rate = 0;
detect-transient = true;
use-damage = true;
log-level = "warn";

wintypes:
{
  tooltip = { shadow = true; full-shadow = false; };
  dock = { shadow = true; clip-shadow-above = true; } # Тень/свечение для Polybar
  dnd = { shadow = false; }
  popup_menu = { opacity = 1.0; }
  dropdown_menu = { opacity = 1.0; }
};
=======
backend = "glx";

# Максимально сильные тени
shadow = true;

# Увеличиваем ширину свечения до 16 пикселей
shadow-radius = 14;

# Сдвигаем координаты строго в минус для равномерности по всему периметру
shadow-offset-x = -14;
shadow-offset-y = -14;
animation = true
# Абсолютная плотность (максимальная сила без прозрачности)
shadow-opacity = 1.0;

# Выставляем чистый, максимально яркий красный цвет (1.0 — это предел)
shadow-red = 1.0;
shadow-green = 0.0;
shadow-blue = 0.1;

# Исключения для панелей (чтобы не затенять бар vxwm)
shadow-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'vxwm'"
];

# Сохраняем острые углы и фикс для vxwm
corner-radius = 0;
frame-opacity = 1.0;

# Жесткая оптимизация для слабого ПК
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
use-damage = true;
vsync = false;
blur-background = false;
fading = false;
unredir-if-possible = true;
>>>>>>> 3050be824cfcb157c8266dd31709c48aa7df5959
