[colors]
# Глубокий матовый черный (основной фон)
background = #0d0d0d
# Темно-серый угольный (для выделения активных элементов)
background-alt = #1a1a1a
# Холодный призрачно-белый (текст и иконки)
foreground = #e6e6e6
# Агрессивный кроваво-красный (акценты, 1000-7)
primary = #cc0000
# Кислотно-алый (второстепенные элементы)
secondary = #ff3333
# Яркий красный (ошибки и предупреждения)
alert = #ff0033
# Мертвый серый (неактивное состояние)
disabled = #404040

[bar/ghoul]
# Режим абсолютного позиционирования на стекле монитора (игнорирует холст)
override-redirect = true
fixed-center = true

# Маленький размер (55% от 2K экрана) и точные координаты снизу
width = 1408
height = 44
offset-x = 576
offset-y = 1384

# Полное скругление углов (капсула)
radius = 18

# Хак для корректной обрезки углов в X11
border-size = 4
border-color = #00000000

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 4pt
padding-left = 3
padding-right = 3
module-margin = 2

# Стандартный системный шрифт
font-0 = monospace;2

# Раскладка модулей (без интернета)
modules-left = xworkspaces
modules-center = date
modules-right = pulseaudio memory cpu

cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true

[module/xworkspaces]
type = internal/xworkspaces

# Стиль для активного (текущего) рабочего стола
label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 2
label-active-foreground = ${colors.primary}

# Стиль для рабочих столов с открытыми окнами
label-occupied = %name%
label-occupied-padding = 2
label-occupied-foreground = ${colors.foreground}

# Стиль для критических алертов
label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

# Стиль для пустых рабочих столов
label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 2

[module/date]
type = internal/date
interval = 5

# Формат времени БЕЗ СЕКУНД с фразой zxc ghoul
date = "%H:%M │ 1000-7"

label = %date%
label-foreground = ${colors.primary}
label-background = ${colors.background-alt}
label-padding = 2

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "VOL "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = "MUTED"
label-muted-foreground = ${colors.disabled}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM "
format-prefix-foreground = ${colors.primary}
label = %percentage_used%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU "
format-prefix-foreground = ${colors.primary}
label = %percentage%%

[settings]
screenchange-reload = true
pseudo-transparency = true
